/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author arthu
 */
public class JanelaGrafico extends javax.swing.JFrame {

    /**
     * Creates new form JanelaGrafico
     */
    
    
    DataSet data = new DataSet(0, 30);
    Grafico graficoDeBarra = new Grafico();
    
    
    
    public JanelaGrafico() {
        initComponents();
        
        this.PanelGraf.setLayout(new BorderLayout());
        this.PanelGraf.add(graficoDeBarra.criarGrafico(data));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGraf = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnGerarDS = new javax.swing.JButton();
        tfValorMax = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfDelay = new javax.swing.JTextField();
        CBmethod = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelGraf.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        PanelGraf.setName(""); // NOI18N
        PanelGraf.setPreferredSize(getPreferredSize());
        PanelGraf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Ordenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnGerarDS.setText("Gerar Datase");
        btnGerarDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarDSActionPerformed(evt);
            }
        });

        tfValorMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorMaxActionPerformed(evt);
            }
        });

        jLabel1.setText("Range:");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel2.setText("Ordenador grafico");

        jLabel3.setText("Delay(ms):");

        CBmethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bubble Sort", "Insetion Sort", " " }));
        CBmethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBmethodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGraf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfValorMax, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CBmethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGerarDS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerarDS)
                    .addComponent(tfValorMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(tfDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBmethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelGraf, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int delay = Integer.parseInt(this.tfDelay.getText().length() > 0 ? this.tfDelay.getText(): "10");
        String method = this.CBmethod.getSelectedItem().toString();
        Thread t;
        this.jButton1.setEnabled(false);
        this.btnGerarDS.setEnabled(false);
        t = new Thread(new Runnable() {
                        
       @Override
       public void run() {
         switch(method){
          case "Bubble Sort":
           
          //Bubble Sort
          for(int i=0; i < data.size(); i++) {
            for(int j=i+1; j < data.size(); j++) {
                Integer f1 = data.getValue(i);
                //Color f1Color = data.getColor(i);
                data.setColor(i, Color.red);
                Integer f2 = data.getValue(j);
                //Color f2Color = data.getColor(j);
                data.setColor(j, Color.red);
                
                PanelGraf.removeAll();
                PanelGraf.add(graficoDeBarra.criarGrafico(data));
                PanelGraf.doLayout();
                try { Thread.sleep (delay); } catch (InterruptedException ex) {}
                
                if(f1.compareTo(f2) > 0) {
                   data.setValue(i, f2);
                   data.setValue(j, f1);
                   
                    
                }else{
                    data.setValue(i, f1);
                    data.setValue(j, f2);
                }
                
                
                
            }
            
           }
          break;
          case "Insetion Sort":
          
          
            //Inner sort
           for (int j = 1; j < data.size(); j++) {
                int current = data.get(j).getValor();
                int i = j-1;
                
                while ((i > -1) && (data.get(i).getValor() > current)) {
                    data.setColor(i, Color.red);
                    data.setColor(i+1, Color.red);
                    try { Thread.sleep (delay); } catch (InterruptedException ex) {}
                    PanelGraf.removeAll();
                    PanelGraf.add(graficoDeBarra.criarGrafico(data));
                    PanelGraf.doLayout();
                    
                    data.setValue(i+1, data.getValue(i));
                    i--;
                    
                    
                }
                
                
                data.setValue(i+1, current);
                
                
            }
           break;

         
         }
         
        PanelGraf.removeAll();
        PanelGraf.add(graficoDeBarra.criarGrafico(data));
        PanelGraf.doLayout();
        jButton1.setEnabled(true);
        btnGerarDS.setEnabled(true);
         }
     });
     t.start();
        
                
                        
        
                 
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfValorMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorMaxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tfValorMaxActionPerformed

    private void btnGerarDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarDSActionPerformed
        // TODO add you handling code here:
       System.out.println("chegou");
       Integer range = Integer.parseInt(this.tfValorMax.getText().length() > 0 ? this.tfValorMax.getText() : "30");
       data = new DataSet(0, range);         
       data.randomize();
       this.PanelGraf.removeAll();
       this.PanelGraf.add(graficoDeBarra.criarGrafico(data));
       this.PanelGraf.doLayout();
    }//GEN-LAST:event_btnGerarDSActionPerformed

    private void CBmethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBmethodActionPerformed
        
    }//GEN-LAST:event_CBmethodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBmethod;
    private javax.swing.JPanel PanelGraf;
    private javax.swing.JButton btnGerarDS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfDelay;
    private javax.swing.JTextField tfValorMax;
    // End of variables declaration//GEN-END:variables
}
